### ISSUE TITLE
Why MrAdvice.Sharp.Test reference Mr.Advice(version:2.8.2) again?

### ISSUE THREAD

**Issue by happysammy** [msadikkose/MrAdvice.Sharp#1]
MrAdvice.Sharp has referenced “Mr.Advice” dll, why reference again in the test program? thanks!

**Comment by msadikkose** [comment]
Since MrAdvice waving the referenced project, it should be also referenced.  
Without it, project will be compiled successfully but behaviour will not be as expected.

If you have any solution, any help (pull request) will be appriciated.

**Comment by happysammy** [comment]
Thanks for your reply. In my .NetCore(2.1) Console App, if I reference the Mr.Advice dll again, the VS2017 can't debug my app, all breakpoints will not work.

**Comment by msadikkose** [comment]
Can you please commit your sample code to github so that I can download and check ?
